import { create, fromBinary, toBinary } from "@bufbuild/protobuf";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import {
  AiService,
  AvailableModelsResponseSchema,
  ChatService,
  StreamUnifiedChatRequestWithToolsSchema,
} from "../src/gen/aiserver/v1/aiserver_pb.js";

describe("generated proto surface", () => {
  it("generates service descriptors for typed Cursor services", () => {
    expect(AiService.typeName).toBe("aiserver.v1.AiService");
    expect(ChatService.typeName).toBe("aiserver.v1.ChatService");
    expect(
      AiService.methods.some((method) => method.name === "AvailableModels"),
    ).toBe(true);
    expect(
      ChatService.methods.some(
        (method) => method.name === "StreamUnifiedChatWithTools",
      ),
    ).toBe(true);
  });

  it("round-trips allowlisted messages through generated schemas", () => {
    const response = create(AvailableModelsResponseSchema, {
      modelNames: ["local-model"],
    });
    const decoded = fromBinary(
      AvailableModelsResponseSchema,
      toBinary(AvailableModelsResponseSchema, response),
    );
    const chat = create(StreamUnifiedChatRequestWithToolsSchema, {
      streamUnifiedChatRequest: {
        modelDetails: { modelName: "local-model" },
      },
    });

    expect(decoded.modelNames).toEqual(["local-model"]);
    expect(chat.streamUnifiedChatRequest?.modelDetails?.modelName).toBe(
      "local-model",
    );
  });

  it("checks in generated model-fusion OpenAPI request/response types", () => {
    const generated = readFileSync(
      "src/gen/model_fusion/cursor_harness_openapi.ts",
      "utf8",
    );

    expect(generated).toContain(
      "This file was auto-generated by openapi-typescript",
    );
    expect(generated).toContain('"/model-fusion/v1/cursor-harness:run"');
    expect(generated).toContain("runCursorHarness");
    expect(generated).toContain("CursorHarnessRunRequest");
    expect(generated).toContain("CursorHarnessRunResult");
  });
});
